### ISSUE TITLE
install is broken.

### ISSUE THREAD

**Issue by TwistingTwists** [bcksl/ash_geo#2]
while updating `config/runtime.exs` it throws the error 

```elixir
ERROR! the application :ash has a different value set for key :custom_types during runtime compared to compile time. Since this application environment entry was marked as compile time, this difference can lead to different behaviour than expected:

  * Compile time value was not set
  * Runtime value was set to: [geometry: AshGeo.Geometry, geo_json: AshGeo.GeoJson, geo_wkt: AshGeo.GeoWkt, geo_wkb: AshGeo.GeoWkb, geo_any: AshGeo.GeoAny]

To fix this error, you might:

  * Make the runtime value match the compile time one

  * Recompile your project. If the misconfigured application is a dependency, you may need to run "mix deps.compile ash --force"

  * Alternatively, you can disable this check. If you are using releases, you can set :validate_compile_env to false in your release configuration. If you are using Mix to start your system, you can pass the --no-validate-compile-env flag



18:14:30.617 [error] Task #PID<0.245.0> started from #PID<0.111.0> terminating
** (stop) "aborting boot"
    (elixir 1.14.5) Config.Provider.boot/2
Function: &:erlang.apply/2
    Args: [#Function<1.127481437/1 in Mix.Tasks.Compile.All.load_apps/3>, [ash: "/home/abhishek/Downloads/experiments_projects/aug2023/companies_reg_ex/_build/dev/lib"]]
** (EXIT from #PID<0.111.0>) an exception was raised:
    ** (ErlangError) Erlang error: "aborting boot"
        (elixir 1.14.5) Config.Provider.boot/2


```

**Comment by TwistingTwists** [comment]
did `mix deps.compile ash --force` to get rid of above issue.

**Comment by TwistingTwists** [comment]
got a new error 

```elixir 
** (UndefinedFunctionError) function Geo.PostGIS.Extension.init/1 is undefined (module Geo.PostGIS.Extension is not available)
    Geo.PostGIS.Extension.init([])
    (postgrex 0.17.2) lib/postgrex/type_module.ex:929: Postgrex.TypeModule.configure/1
    (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (postgrex 0.17.2) lib/postgrex/type_module.ex:11: Postgrex.TypeModule.define/3
    (stdlib 4.3) erl_eval.erl:744: :erl_eval.do_apply/7
    (stdlib 4.3) erl_eval.erl:136: :erl_eval.exprs/6

```

**Comment by TwistingTwists** [comment]
https://github.com/bcksl/ash_geo/blob/main/mix.exs#L43

after adding this dependency manually, it works. 

Proposed solution:  remove the `:test` from the deps ?

**Comment by bcksl** [comment]
This is very much by design. Because this package contains functionality based on a number of packages, not all of which may be used in every application, those dependencies are optional and must be installed alongside `ash_geo`. I've added a note to the readme with some guidance.
